### ISSUE TITLE
Game doesn't launch on MacOS with latest dev build. (2.1.0 dev3)

### ISSUE THREAD

**Issue by popdynamite5511** [MinicraftPlus/minicraft-plus-revived#347]
**Describe the bug**
Game doesn't work, gives error. I tried the older versions, they work fine.

**To Reproduce**
Open the program.
Popup with error appears 
org.json.JSONException: JSONObject["resourcePack"] not found.
	at org.json.JSONObject.get(JSONObject.java:580)
	at org.json.JSONObject.getString(JSONObject.java:867)
	at minicraft.saveload.Load.loadPrefs(Load.java:402)
	at minicraft.saveload.Load.<init>(Load.java:131)
	at minicraft.core.Game.main(Game.java:119)

**Expected behavior**
Program should work

**Desktop:**
 - OS: Mac OSX 10.11.6
 - Version of Minicraft: 2.1.0 dev3

**Comment by Litorom** [comment]
It’s a conversion error. To fix go to the game directory and deleted the pref and unlocks json files.

**Comment by Makkkkus** [comment]
Fixed
