### ISSUE TITLE
LMAO bug

### ISSUE THREAD

**Issue by swyat1911** [MinicraftPlus/minicraft-plus-revived#453]
i started fishing, walked away and crashed a game lmao
Unhandled error: General Application Crash
java.lang.ExceptionInInitializerError
	at minicraft.entity.mob.Player.goFishing(Player.java:630)
	at minicraft.entity.mob.Player.tick(Player.java:216)
	at minicraft.core.Updater.tick(Updater.java:196)
	at minicraft.core.Initializer.run(Initializer.java:81)
	at minicraft.core.Game.main(Game.java:93)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Unknown Source)
	at java.io.InputStreamReader.<init>(Unknown Source)
	at minicraft.saveload.Load.loadFile(Load.java:153)
	at minicraft.item.FishingData.getData(FishingData.java:22)
	at minicraft.item.FishingData.<clinit>(FishingData.java:11)
	... 5 more
![obraz](https://user-images.githubusercontent.com/127844355/224979908-2f2898c3-66f3-42c1-baf9-eeb582d26995.png)

**Comment by swyat1911** [comment]
edit: it litylelary crash evry time you try to fish lol

**Comment by Litorom** [comment]
You didn’t specify what version, only 2.1.3 and 2.2.0-dev2 we care about

**Comment by BenCheung0422** [comment]
This has already been resolved by #431, which will be included in the coming release.
