### ISSUE TITLE
canvas init error on macos x

### ISSUE THREAD

**Issue by vvv112** [MinicraftPlus/minicraft-plus-revived#465]
Unexpected error: Canvas Initialization Failure: The canvas is unable to be initialized.
java.awt.AWTException: Only double buffering is supported
	at java.desktop/sun.java2d.metal.MTLGraphicsConfig.assertOperationSupported(MTLGraphicsConfig.java:274)
	at java.desktop/sun.lwawt.LWComponentPeer.createBuffers(LWComponentPeer.java:515)
	at java.desktop/java.awt.Component$FlipBufferStrategy.createBuffers(Component.java:4116)
	at java.desktop/java.awt.Component$FlipBufferStrategy.<init>(Component.java:4058)
	at java.desktop/java.awt.Component$FlipSubRegionBufferStrategy.<init>(Component.java:4592)
	at java.desktop/java.awt.Component.createBufferStrategy(Component.java:3921)
	at java.desktop/java.awt.Canvas.createBufferStrategy(Canvas.java:201)
	at minicraft.core.Renderer.initScreen(Renderer.java:114)
	at minicraft.core.Game.main(Game.java:80)

**Comment by vvv112** [comment]
java version "20" 2023-03-21
Java(TM) SE Runtime Environment (build 20+36-2344)

**Comment by zielony12** [comment]
they make game for windows 🤦

**Comment by vvv112** [comment]
that is javaVM, is crossplatform

**Comment by zielony12** [comment]
@vvv112  yea but it will crash on other platforms like in this issue

**Comment by vvv112** [comment]
is that fixed now?

**Comment by Makkkkus** [comment]
Yes
