### ISSUE TITLE
Audio doesn't work on Archlinux

### ISSUE THREAD

**Issue by zielony12** [MinicraftPlus/minicraft-plus-revived#473]
**Description of the bug**
Audio won't load; It says:
```
[zielony12@archlinux Downloads]$ java -jar minicraft_plus-2.1.3.jar 
DEBUG: Determined gameDir: /home/karol/.playminicraft/mods/Minicraft_Plus
DEBUG: Initializing tile list...
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1322)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1091)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1193)
	at minicraft.core.io.Sound.<init>(Sound.java:73)
	at minicraft.core.io.Sound.<clinit>(Sound.java:20)
	at minicraft.core.Game.main(Game.java:114)
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1322)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1091)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1193)
	at minicraft.core.io.Sound.<init>(Sound.java:73)
	at minicraft.core.io.Sound.<clinit>(Sound.java:21)
	at minicraft.core.Game.main(Game.java:114)
ERROR: Could not load sound file /resources/sound/death.wav
ERROR: Could not load sound file /resources/sound/monsterhurt.wav
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1322)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1091)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1193)
	at minicraft.core.io.Sound.<init>(Sound.java:73)
	at minicraft.core.io.Sound.<clinit>(Sound.java:22)
	at minicraft.core.Game.main(Game.java:114)
ERROR: Could not load sound file /resources/sound/bossdeath.wav
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1322)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1091)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1193)
	at minicraft.core.io.Sound.<init>(Sound.java:73)
	at minicraft.core.io.Sound.<clinit>(Sound.java:23)
	at minicraft.core.Game.main(Game.java:114)
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1322)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1091)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1193)
	at minicraft.core.io.Sound.<init>(Sound.java:73)
	at minicraft.core.io.Sound.<clinit>(Sound.java:24)
	at minicraft.core.Game.main(Game.java:114)
ERROR: Could not load sound file /resources/sound/fuse.wav
ERROR: Could not load sound file /resources/sound/explode.wav
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1322)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1091)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1193)
	at minicraft.core.io.Sound.<init>(Sound.java:73)
	at minicraft.core.io.Sound.<clinit>(Sound.java:25)
	at minicraft.core.Game.main(Game.java:114)
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1322)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1091)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1193)
	at minicraft.core.io.Sound.<init>(Sound.java:73)
	at minicraft.core.io.Sound.<clinit>(Sound.java:26)
	at minicraft.core.Game.main(Game.java:114)
ERROR: Could not load sound file /resources/sound/pickup.wav
ERROR: Could not load sound file /resources/sound/craft.wav
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1322)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1091)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1193)
	at minicraft.core.io.Sound.<init>(Sound.java:73)
	at minicraft.core.io.Sound.<clinit>(Sound.java:27)
	at minicraft.core.Game.main(Game.java:114)
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1322)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1091)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1193)
	at minicraft.core.io.Sound.<init>(Sound.java:73)
	at minicraft.core.io.Sound.<clinit>(Sound.java:28)
	at minicraft.core.Game.main(Game.java:114)
ERROR: Could not load sound file /resources/sound/craft.wav
ERROR: Could not load sound file /resources/sound/craft.wav
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1322)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1091)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1193)
	at minicraft.core.io.Sound.<init>(Sound.java:73)
	at minicraft.core.io.Sound.<clinit>(Sound.java:29)
	at minicraft.core.Game.main(Game.java:114)
ERROR: Could not load sound file /resources/sound/select.wav
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1322)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:120)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1091)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1193)
	at minicraft.core.io.Sound.<init>(Sound.java:73)
	at minicraft.core.io.Sound.<clinit>(Sound.java:30)
	at minicraft.core.Game.main(Game.java:114)
ERROR: Could not load sound file /resources/sound/confirm.wav

```

**Expected behavior**
I expected it to load and play audio. 

**Desktop**
 - OS: Archlinux linux 6.2.13-arch1-1
 - Game version: 2.1.3

**Additional info**
I'm not sure if it counts as a bug, or I should mark this as a feature request. I have experienced this bug before and I think it's alsa's or pulseaudio's fault. I think that you should have changed the audio backend to anything else, guys. Minecraft, that uses lwjgl3 works well btw.

**Comment by Makkkkus** [comment]
Hence why I put it as a goal to move to the ogg format.

**Comment by BenCheung0422** [comment]
Does this problem also occur on other platforms or Linux distributions?

**Comment by BenCheung0422** [comment]
This exception might also occur if the sound card or the sound card driver installed does not support the PCM format. Most of the operation systems should support various 8-bit and 16-bit format, especially PCM. Java Sound library makes support for PCM in WAV on Linux, MacOS, Windows and Oracle Solaris.

**Comment by BenCheung0422** [comment]
I have tested with the latest Arch Linux by using its live USB ISO (GNOME version), in which I can run the game without the errors mentioned. Also, I recommend using PipeWire over PulseAudio as I noticed that I can experience high audio latency with PulseAudio in game. Please make sure that you have configured your audio system correctly, and compatible.

**Comment by BenCheung0422** [comment]
Furthermore, PCM is the most widely supported audio format. PCM is developed and being mature in the late 20th century. 16 bit LPCM is defined by [RFC 2586 (proposed on 1999)](https://datatracker.ietf.org/doc/html/rfc2586), 44.1kHz is as CD quality, so it does not make sense that it is not supported by modern devices while nearly all devices support it.
