### ISSUE TITLE
Opening inventory while fishing crashes the game.

### ISSUE THREAD

**Issue by Dioarya** [MinicraftPlus/minicraft-plus-revived#496]
**Describe the bug**
When the fishing rod is out while fishing, pressing the inventory button crashes the game.

**To Reproduce**
1. Fish in the water
2. Press inventory button

**Expected behavior**
Opens the inventory and cancels the fishing

**Desktop (please complete the following information):**
OS: Windows
Game Version: 2.2.0-dev3

**Additional context**
Unhandled error: General Application Crash
java.lang.NullPointerException: Cannot read field "sprite" because "this.activeItem" is null
	at minicraft.entity.mob.Player.render(Player.java:928)
	at minicraft.level.Level.sortAndRender(Level.java:491)
	at minicraft.level.Level.renderSprites(Level.java:454)
	at minicraft.core.Renderer.renderLevel(Renderer.java:223)
	at minicraft.core.Renderer.render(Renderer.java:133)
	at minicraft.core.Initializer.run(Initializer.java:97)
	at minicraft.core.Game.main(Game.java:93)

**Comment by BenCheung0422** [comment]
This has already been fixed by #462, so it will be included in the next pre-release.

**Comment by Dioarya** [comment]
I'm sorry for not checking if it's a known bug first...
