### ISSUE TITLE
Start Crash

### ISSUE THREAD

**Issue by HinataNekoNya** [MinicraftPlus/minicraft-plus-revived#564]
```
Unhandled error: General Application Crash
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.remove(Unknown Source)
	at minicraft.saveload.Load.loadPrefsOld(Load.java:493)
	at minicraft.saveload.Load.<init>(Load.java:212)
	at minicraft.core.Game.main(Game.java:84)
```

Double click to launch the game and get the error

 - OS: Windows
 - Game version: 2.2.0 dev3
 - Java: 8u381

**Comment by BenCheung0422** [comment]
What is your previous game version?

**Comment by HinataNekoNya** [comment]
2.0.7
